name = "HTLogger"
uuid = "1397e390-a8f5-4f51-a94c-8e6ea99caba8"
authors = ["MLackner <lacknersmichael@gmail.com> and contributors"]
version = "0.2.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
SerialPorts = "5d0f9de7-4c7f-54f5-bec2-484e8c04014e"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
